### ISSUE TITLE
Questions and issue

### ISSUE THREAD

**Issue by FusionInfo1** [DevKanui/FMI-off-automatisation#2]
Hi there, thanks for your script. Followed the guide, everything seems to run, however i have 2 questions.

Can a SN be used instead of an IMEI for a Wifi only ipad ?

I've tried with one and it loops, the browser opens up over and over generating a new email everytime and it won't stop until i close it. Is it because of the SN being used instead of the IMEI ? Thanks .

**Comment by FusionInfo1** [comment]
I'm also getting this error : Fehler bei IMEI 3560820944XXXX: ERROR_WRONG_USER_KEY

**Comment by DevKanui** [comment]
Yeah, you should be able to run serial numbers, there may be a problem with how you run the script if it loops. But in the test phase, we only tested like 3 so we maybe haven't tested it enough.

the error however seems to be a problem with your API key maybe copy-paste it again to make sure it's correct. if you still encounter this error. please send me the steps to reproduce it. Also send the whole stack trace it easier to work with

**Comment by FusionInfo1** [comment]
Here are my 2 api keys, triple checked (i removed last digit for security) 

Is the format OK?

TwoCaptcha = 56a7198ac25b0cb256ee6901f8732fb
sickw = GQD-UO2-PFC-47X-5T5-CTM-6T6-O8

**Comment by FusionInfo1** [comment]
Here is the output : 

C:\skript>py checkbox.py
35608209448860X
Your mailbox is empty. Hold tight. Mailbox is refreshed automatically every 5 seconds.
DevTools listening on ws://127.0.0.1:57652/devtools/browser/0c451299-e2cb-4084-9191-1a1460cdf9ec
Opened the URL
Scrolled to the checkbox
Clicked the checkbox
Clicked the 'Continue' button
Filled email address
Filled serial number
Image screenshot captured and saved
None
Fehler bei IMEI 35608209448860X: ERROR_WRONG_USER_KEY

**Comment by DevKanui** [comment]
Okay seems like your TwoCaptcha code isn't loading in and now ik why try pip install dotenv that should fix it
