### ISSUE TITLE
ModuleNotFoundError: No module named 'dotenv'

### ISSUE THREAD

**Issue by axi6ne8us** [DevKanui/FMI-off-automatisation#3]
I tried, but ran into this error:
C:\Users\Bhagiratha\Desktop\FMI-off-automatisation-main\skript>py checkbox.py
Traceback (most recent call last):
  File "C:\Users\Bhagiratha\Desktop\FMI-off-automatisation-main\skript\checkbox.py", line 2, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'

C:\Users\Bhagiratha\Desktop\FMI-off-automatisation-main\skript>

**Comment by DevKanui** [comment]
Try pip install python-dotenv and restart the cmd after

**Comment by DevKanui** [comment]
Make sure you did install the requirements txt as stated in the quick tutorial

**Comment by axi6ne8us** [comment]
Yes, I did the requirements.txt install without errors.  but I get this when installing dotenv

C:\Windows\System32>pip install python-dotenv
Requirement already satisfied: python-dotenv in c:\users\bhagiratha\appdata\local\programs\python\python310\lib\site-packages (1.0.0)

**Comment by DevKanui** [comment]
That’s weird please install visual studio code and open the checkbox.py install the recommended compilers(will appear on the bottom) send me a screenshot of the from parts

**Comment by axi6ne8us** [comment]
![checkbox-Screenshot](https://github.com/DevKanui/FMI-off-automatisation/assets/13624000/a2057884-a6ba-44f4-97a9-44967b8e80de)

**Comment by DevKanui** [comment]
Yeah this should only happen when requirements aren’t installed can you open a terminal in vs code and do it again in that terminal?

**Comment by axi6ne8us** [comment]
same error happens
![checkbox-vsc-terminal](https://github.com/DevKanui/FMI-off-automatisation/assets/13624000/8f08a69d-2a1e-4a62-b931-1aa36cc4ac0d)

**Comment by axi6ne8us** [comment]
I tried with a clean Windows 10 install system, but still getting those errors:
[clean-win-install-errors.txt](https://github.com/DevKanui/FMI-off-automatisation/files/12423556/clean-win-install-errors.txt)

**Comment by DevKanui** [comment]
hey when you got some time maybe send me your anydesk and i could check it

**Comment by axi6ne8us** [comment]
I managed to get the script to run, but now getting output "Cloud management controller initialization aborted as CBCM is not enabled"  How to solve this problem?
