### ISSUE TITLE
selenium-manager.exe - Application Error

### ISSUE THREAD

**Issue by uNiCo15** [DevKanui/FMI-off-automatisation#4]
@DevKanui 

![ISSUE](https://github.com/DevKanui/FMI-off-automatisation/assets/123725274/04d6954d-4dfe-4800-bc47-c10a47bab9d4)

i got this error and keeps appearing after i click ok button.

**Comment by DevKanui** [comment]
Hey could you send some steps how you achieved this error sorry for the late reply was busy

**Comment by uNiCo15** [comment]
hello, it seems that my windows is the problem... so i tried it in my other laptop but i have a different problem

![image](https://github.com/DevKanui/FMI-off-automatisation/assets/123725274/046efa87-2730-40e6-aac3-6c8cb4165abf)

![image](https://github.com/DevKanui/FMI-off-automatisation/assets/123725274/ba0ad854-dcb6-4fe2-b87b-20ffcb46fbea)

it says ERROR_WRONG_USER_KEY
